# Generated by Django 6.0.7 on 2026-08-07 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0005_delete_city'),
        ('sites', '0003_site_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='provinces.district'),
        ),
        migrations.AlterField(
            model_name='site',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='provinces.town'),
        ),
    ]
