# Generated by Django 6.0.7 on 2026-08-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0006_alter_town_unique_together_remove_town_district'),
        ('sites', '0004_site_district_alter_site_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='town',
        ),
        migrations.AlterField(
            model_name='site',
            name='district',
            field=models.ForeignKey(default='e0c7409a-36fa-4389-916a-65c6b4d914b3', on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='provinces.district'),
            preserve_default=False,
        ),
    ]
