# Generated by Django 6.0.7 on 2026-07-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0002_alter_city_options_city_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
