# Generated by Django 6.0.7 on 2026-08-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0005_delete_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='town',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='town',
            name='district',
        ),
    ]
