# Generated by Django 6.0.7 on 2026-08-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0006_alter_town_unique_together_remove_town_district'),
        ('sites', '0005_remove_site_town_alter_site_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Town',
        ),
    ]
