# Generated by Django 6.0.7 on 2026-07-17 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UPLOADING', 'Uploading'), ('PARSING', 'Parsing'), ('READY', 'Ready'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('template', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boqs', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=20)),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discipline', models.CharField(choices=[('CIVIL', 'Civil'), ('ELECTRICAL', 'Electrical'), ('FIBER', 'Fiber'), ('CONDUIT', 'Conduit'), ('NETWORKING', 'Networking')], max_length=20)),
                ('installation_method', models.CharField(blank=True, max_length=100, null=True)),
                ('specified_vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_tolerance_pct', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boq.boq')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
