# Generated by Django 6.0.7 on 2026-07-22 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0002_boq_site'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boqs', to='sites.site'),
        ),
    ]
