# Generated by Django 6.0.7 on 2026-08-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0004_boqitem_full_spreadsheet_schema'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boqitem',
            unique_together={('boq', 'item', 'no', 'model')},
        ),
    ]
