# Generated by Django 6.0.7 on 2026-08-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0005_alter_boqitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boqitem',
            unique_together=set(),
        ),
    ]
