# Generated by Django 6.0.7 on 2026-08-24 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0007_boqtemplate_alter_boq_template'),
        ('sites', '0004_site_district_alter_site_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boqs', to='sites.site'),
        ),
    ]
