# Generated by Django 6.0.7 on 2026-08-20 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0007_boqtemplate_alter_boq_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQSurveyData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DISTRICT', 'District-level breakdown only'), ('SITE', 'Site-level breakdown (implies districts too)')], help_text='Whether survey goes down to Site level or just District', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Parsed survey: {items: [{item_id, item_type, model_name, allocations: [{district, site, qty, ...}]}]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_data', to='boq.boq')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BOQ Survey Data',
                'unique_together': {('boq',)},
            },
        ),
    ]
