# Generated by Django 5.2.15 on 2026-07-24 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_site_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('unit', models.CharField(default='m', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('kpi_schema', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteProgressTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('unit', models.CharField(default='m', max_length=30)),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('kpi_schema', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tasks', to='sites.site')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_tasks', to='progress.progresstasktemplate')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('site', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DailyProgressEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('kpi_values', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True, default='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='sites.site')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_progress_entries', to=settings.AUTH_USER_MODEL)),
                ('site_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='progress.siteprogresstask')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('site_task', 'date')},
            },
        ),
    ]
