# Generated by Django 5.2.15 on 2026-07-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0004_boqitem_full_spreadsheet_schema'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprogresstask',
            name='boq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_tasks', to='boq.boq'),
        ),
        migrations.AddField(
            model_name='siteprogresstask',
            name='boq_item',
            field=models.ForeignKey(blank=True, help_text='When set, planned qty defaults from BOQ item and daily logs update actual_quantity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_tasks', to='boq.boqitem'),
        ),
    ]
