# Generated by Django 6.0.7 on 2026-08-05 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_siteprogresstask_boq_siteprogresstask_boq_item'),
        ('sites', '0003_site_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_categories', to='sites.site')),
            ],
            options={
                'verbose_name_plural': 'KPI categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.AddField(
            model_name='siteprogresstask',
            name='kpi_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='progress.kpicategory'),
        ),
    ]
