# Generated by Django 6.0.7 on 2026-08-09 22:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_kpicategory_siteprogresstask_kpi_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default_unit', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Item catalog entries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleCatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Module catalog entries',
                'ordering': ['name'],
            },
        ),
    ]
