# Generated by Django 6.0.7 on 2026-08-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_itemcatalogentry_modulecatalogentry'),
    ]

    operations = [
    ]
