# Generated by Django 6.0.7 on 2026-08-27 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_add_project_district_scope'),
        ('projects', '0001_initial'),
        ('provinces', '0007_delete_town'),
        ('sites', '0005_remove_site_town_alter_site_district'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kpicategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='siteprogresstask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kpicategory',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_categories', to='provinces.district'),
        ),
        migrations.AddField(
            model_name='kpicategory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_categories', to='projects.project'),
        ),
        migrations.AddField(
            model_name='siteprogresstask',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_tasks', to='provinces.district'),
        ),
        migrations.AddField(
            model_name='siteprogresstask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_tasks', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='dailyprogressentry',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='kpicategory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_categories', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='siteprogresstask',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_tasks', to='sites.site'),
        ),
        migrations.AlterUniqueTogether(
            name='kpicategory',
            unique_together={('project', 'district', 'site', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='siteprogresstask',
            unique_together={('project', 'district', 'site', 'key')},
        ),
    ]
