# Generated by Django 6.0.7 on 2026-08-27 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_backfill_scope'),
        ('projects', '0001_initial'),
        ('provinces', '0007_delete_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpicategory',
            name='district',
            field=models.ForeignKey(default='e0c7409a-36fa-4389-916a-65c6b4d914b3', on_delete=django.db.models.deletion.CASCADE, related_name='kpi_categories', to='provinces.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpicategory',
            name='project',
            field=models.ForeignKey(default='15430809-30a1-485f-a643-d612fb486826', on_delete=django.db.models.deletion.CASCADE, related_name='kpi_categories', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteprogresstask',
            name='district',
            field=models.ForeignKey(default='e0c7409a-36fa-4389-916a-65c6b4d914b3', on_delete=django.db.models.deletion.CASCADE, related_name='progress_tasks', to='provinces.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteprogresstask',
            name='project',
            field=models.ForeignKey(default='15430809-30a1-485f-a643-d612fb486826', on_delete=django.db.models.deletion.CASCADE, related_name='progress_tasks', to='projects.project'),
            preserve_default=False,
        ),
    ]
