# Generated by Django 6.0.7 on 2026-07-23 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(blank=True, choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.module'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('module', 'action')},
        ),
    ]
