# Generated by Django 6.0.7 on 2026-08-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyitem',
            options={'ordering': ['row_number']},
        ),
        migrations.RenameField(
            model_name='surveyitem',
            old_name='extra_fields',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='surveyitem',
            name='district',
        ),
        migrations.RemoveField(
            model_name='surveyitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='surveyitem',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='surveyitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='surveyitem',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='surveyitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='surveyitem',
            name='row_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
