# Generated by Django 6.0.7 on 2026-07-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='SITE_ENG', max_length=50),
        ),
    ]
